"""create alert tables

Revision ID: 15e6f5d4d248
Revises: 2f4516992979
Create Date: 2026-03-15 07:38:45.193815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15e6f5d4d248'
down_revision: Union[str, Sequence[str], None] = '2f4516992979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=False),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=False),
    sa.Column('quiet_hours_tz', sa.String(length=64), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_alert_settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('pair', sa.String(length=32), nullable=True),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('condition', sa.String(length=32), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('secondary_threshold', sa.Float(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('peak_value', sa.Float(), nullable=True),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_one_shot', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_type_active', 'alerts', ['type', 'is_active'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('alert_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_value', sa.Float(), nullable=False),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_history_alert_triggered', 'alert_history', ['alert_id', 'triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_history_alert_triggered', table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index('ix_alert_type_active', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('alert_settings')
    # ### end Alembic commands ###
