"""add performance_tracker table

Revision ID: 18b516591cc5
Revises: 15e6f5d4d248
Create Date: 2026-03-15 09:51:45.493737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b516591cc5'
down_revision: Union[str, Sequence[str], None] = '15e6f5d4d248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_tracker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('current_sl_atr', sa.Float(), nullable=False),
    sa.Column('current_tp1_atr', sa.Float(), nullable=False),
    sa.Column('current_tp2_atr', sa.Float(), nullable=False),
    sa.Column('last_optimized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_optimized_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair', 'timeframe', name='uq_tracker_pair_timeframe')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_tracker')
    # ### end Alembic commands ###
