"""add agent_analyses table

Revision ID: 25d2b7bbcb70
Revises: f598aa9c7321
Create Date: 2026-04-09 06:42:54.589147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25d2b7bbcb70'
down_revision: Union[str, Sequence[str], None] = 'f598aa9c7321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('pair', sa.String(length=32), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_analysis_created', 'agent_analyses', ['created_at'], unique=False)
    op.create_index('ix_agent_analysis_pair_type', 'agent_analyses', ['pair', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_analysis_pair_type', table_name='agent_analyses')
    op.drop_index('ix_agent_analysis_created', table_name='agent_analyses')
    op.drop_table('agent_analyses')
    # ### end Alembic commands ###
