"""add pipeline_evaluations table

Revision ID: 3fb959be4e78
Revises: b5c6d7e8f9a0
Create Date: 2026-03-29 12:35:43.747743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fb959be4e78'
down_revision: Union[str, Sequence[str], None] = 'b5c6d7e8f9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('emitted', sa.Boolean(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('effective_threshold', sa.Integer(), nullable=False),
    sa.Column('tech_score', sa.Integer(), nullable=False),
    sa.Column('flow_score', sa.Integer(), nullable=False),
    sa.Column('onchain_score', sa.Integer(), nullable=True),
    sa.Column('pattern_score', sa.Integer(), nullable=True),
    sa.Column('liquidation_score', sa.Integer(), nullable=True),
    sa.Column('confluence_score', sa.Integer(), nullable=True),
    sa.Column('indicator_preliminary', sa.Integer(), nullable=False),
    sa.Column('blended_score', sa.Integer(), nullable=False),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('llm_contribution', sa.Integer(), nullable=False),
    sa.Column('ml_agreement', sa.String(length=16), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regime', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('availabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_eval_pair_time', 'pipeline_evaluations', ['pair', 'evaluated_at'], unique=False)
    op.create_index('ix_pipeline_eval_time', 'pipeline_evaluations', ['evaluated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipeline_eval_time', table_name='pipeline_evaluations')
    op.drop_index('ix_pipeline_eval_pair_time', table_name='pipeline_evaluations')
    op.drop_table('pipeline_evaluations')
    # ### end Alembic commands ###
