"""create candles and signals tables

Revision ID: 40c06f2d45a2
Revises: 
Create Date: 2026-02-27 03:28:42.076708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40c06f2d45a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair', 'timeframe', 'timestamp', name='uq_candle')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('traditional_score', sa.Integer(), nullable=False),
    sa.Column('llm_opinion', sa.String(length=16), nullable=True),
    sa.Column('llm_confidence', sa.String(length=8), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('entry', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('take_profit_1', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('take_profit_2', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('raw_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_pair_tf_created', 'signals', ['pair', 'timeframe', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signal_pair_tf_created', table_name='signals')
    op.drop_table('signals')
    op.drop_table('candles')
    # ### end Alembic commands ###
