"""add cvd_delta to order_flow_snapshots

Revision ID: 420e0f00c050
Revises: 8d4b8177ab5a
Create Date: 2026-03-25 08:43:56.898838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420e0f00c050'
down_revision: Union[str, Sequence[str], None] = '8d4b8177ab5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_flow_snapshots', sa.Column('cvd_delta', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_flow_snapshots', 'cvd_delta')
    # ### end Alembic commands ###
