"""add confidence_tier and adx_center columns

Revision ID: 4cdbd440d919
Revises: a7b8c9d0e1f2
Create Date: 2026-03-24 10:48:49.346709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdbd440d919'
down_revision: Union[str, Sequence[str], None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regime_weights', sa.Column('adx_center', sa.Float(), server_default='20.0', nullable=False))
    op.add_column('signals', sa.Column('confidence_tier', sa.String(length=8), server_default='medium', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'confidence_tier')
    op.drop_column('regime_weights', 'adx_center')
    # ### end Alembic commands ###
