"""add engine_snapshot and parameter_overrides columns

Revision ID: 4d65240c2b2d
Revises: a9f1b2c3d4e5
Create Date: 2026-03-20 17:28:57.946602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d65240c2b2d'
down_revision: Union[str, Sequence[str], None] = 'a9f1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('parameter_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('pipeline_settings', sa.Column('traditional_weight', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('flow_weight', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('onchain_weight', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('pattern_weight', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('ml_blend_weight', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('ml_confidence_threshold', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('llm_threshold', sa.Integer(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('llm_factor_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('pipeline_settings', sa.Column('llm_factor_total_cap', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('confluence_max_score', sa.Integer(), nullable=True))
    op.add_column('signals', sa.Column('engine_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'engine_snapshot')
    op.drop_column('pipeline_settings', 'confluence_max_score')
    op.drop_column('pipeline_settings', 'llm_factor_total_cap')
    op.drop_column('pipeline_settings', 'llm_factor_weights')
    op.drop_column('pipeline_settings', 'llm_threshold')
    op.drop_column('pipeline_settings', 'ml_confidence_threshold')
    op.drop_column('pipeline_settings', 'ml_blend_weight')
    op.drop_column('pipeline_settings', 'pattern_weight')
    op.drop_column('pipeline_settings', 'onchain_weight')
    op.drop_column('pipeline_settings', 'flow_weight')
    op.drop_column('pipeline_settings', 'traditional_weight')
    op.drop_column('backtest_runs', 'parameter_overrides')
    # ### end Alembic commands ###
