"""add ml weight min max columns to pipeline_settings

Revision ID: 55bc9e777b6e
Revises: 9888b8f01368
Create Date: 2026-03-30 19:52:17.301076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bc9e777b6e'
down_revision: Union[str, Sequence[str], None] = '9888b8f01368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('pipeline_settings', sa.Column('ml_weight_min', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('ml_weight_max', sa.Float(), nullable=True))
    # Deduplicate before adding unique constraint
    op.execute("""
        DELETE FROM source_ic_history
        WHERE id NOT IN (
            SELECT MIN(id) FROM source_ic_history
            GROUP BY source, pair, timeframe, date
        )
    """)
    op.create_unique_constraint('uq_source_ic_per_day', 'source_ic_history', ['source', 'pair', 'timeframe', 'date'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_source_ic_per_day', 'source_ic_history', type_='unique')
    op.drop_column('pipeline_settings', 'ml_weight_max')
    op.drop_column('pipeline_settings', 'ml_weight_min')
    # ### end Alembic commands ###
