"""add parameter_proposals and shadow_results tables

Revision ID: 5803ce41ea54
Revises: da3f73fd3440
Create Date: 2026-03-22 19:57:04.391979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5803ce41ea54'
down_revision: Union[str, Sequence[str], None] = 'da3f73fd3440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parameter_group', sa.String(length=50), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('backtest_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shadow_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shadow_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shadow_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('shadow_score', sa.Float(), nullable=False),
    sa.Column('shadow_entry', sa.Float(), nullable=False),
    sa.Column('shadow_sl', sa.Float(), nullable=False),
    sa.Column('shadow_tp1', sa.Float(), nullable=False),
    sa.Column('shadow_tp2', sa.Float(), nullable=False),
    sa.Column('shadow_outcome', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['parameter_proposals.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_results_proposal_id'), 'shadow_results', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_shadow_results_signal_id'), 'shadow_results', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shadow_results_signal_id'), table_name='shadow_results')
    op.drop_index(op.f('ix_shadow_results_proposal_id'), table_name='shadow_results')
    op.drop_table('shadow_results')
    op.drop_table('parameter_proposals')
    # ### end Alembic commands ###
