"""add llm factor calibration

Revision ID: 5fc72700a4c1
Revises: c00a664dc61d
Create Date: 2026-03-31 20:18:27.211201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc72700a4c1'
down_revision: Union[str, Sequence[str], None] = 'c00a664dc61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_factor_outcome',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=32), nullable=False),
    sa.Column('factor_type', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_factor_outcome_type_resolved', 'llm_factor_outcome', ['factor_type', sa.literal_column('resolved_at DESC')], unique=False)
    op.add_column('pipeline_settings', sa.Column('calibration_window', sa.Integer(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('calibration_floor', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_settings', 'calibration_floor')
    op.drop_column('pipeline_settings', 'calibration_window')
    op.drop_index('ix_llm_factor_outcome_type_resolved', table_name='llm_factor_outcome')
    op.drop_table('llm_factor_outcome')
    # ### end Alembic commands ###
