"""add drift detection columns to pipeline_settings

Revision ID: 7501196287dd
Revises: b3a4e7f12d01
Create Date: 2026-03-31 04:55:36.639886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7501196287dd'
down_revision: Union[str, Sequence[str], None] = 'b3a4e7f12d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_settings', sa.Column('drift_psi_moderate', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('drift_psi_severe', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('drift_penalty_moderate', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('drift_penalty_severe', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_settings', 'drift_penalty_severe')
    op.drop_column('pipeline_settings', 'drift_penalty_moderate')
    op.drop_column('pipeline_settings', 'drift_psi_severe')
    op.drop_column('pipeline_settings', 'drift_psi_moderate')
    # ### end Alembic commands ###
