"""signal engine v2 data sources and threshold

Revision ID: 8d4b8177ab5a
Revises: 4cdbd440d919
Create Date: 2026-03-24 16:53:38.165978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4b8177ab5a'
down_revision: Union[str, Sequence[str], None] = '4cdbd440d919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_ic_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('pair', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ic_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_ic_source_pair_date', 'source_ic_history', ['source', 'pair', 'date'], unique=False)
    op.add_column('regime_weights', sa.Column('trending_liquidation_weight', sa.Float(), server_default='0.08', nullable=False))
    op.add_column('regime_weights', sa.Column('ranging_liquidation_weight', sa.Float(), server_default='0.09', nullable=False))
    op.add_column('regime_weights', sa.Column('volatile_liquidation_weight', sa.Float(), server_default='0.11', nullable=False))
    op.add_column('regime_weights', sa.Column('steady_liquidation_weight', sa.Float(), server_default='0.08', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regime_weights', 'steady_liquidation_weight')
    op.drop_column('regime_weights', 'volatile_liquidation_weight')
    op.drop_column('regime_weights', 'ranging_liquidation_weight')
    op.drop_column('regime_weights', 'trending_liquidation_weight')
    op.drop_index('ix_source_ic_source_pair_date', table_name='source_ic_history')
    op.drop_table('source_ic_history')
    # ### end Alembic commands ###
