"""add liquidation tunable columns to pipeline_settings

Revision ID: 8fac78ecf858
Revises: 9c43c372fcf9
Create Date: 2026-03-27 06:16:21.257791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fac78ecf858'
down_revision: Union[str, Sequence[str], None] = '9c43c372fcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_settings', sa.Column('liquidation_weight', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('liquidation_cluster_max_score', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('liquidation_asymmetry_max_score', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('liquidation_cluster_weight', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('liquidation_proximity_steepness', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('liquidation_decay_half_life_hours', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('liquidation_asymmetry_steepness', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_settings', 'liquidation_asymmetry_steepness')
    op.drop_column('pipeline_settings', 'liquidation_decay_half_life_hours')
    op.drop_column('pipeline_settings', 'liquidation_proximity_steepness')
    op.drop_column('pipeline_settings', 'liquidation_cluster_weight')
    op.drop_column('pipeline_settings', 'liquidation_asymmetry_max_score')
    op.drop_column('pipeline_settings', 'liquidation_cluster_max_score')
    op.drop_column('pipeline_settings', 'liquidation_weight')
    # ### end Alembic commands ###
