"""add pattern override columns to pipeline_settings

Revision ID: 9c43c372fcf9
Revises: 420e0f00c050
Create Date: 2026-03-27 05:34:02.883081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c43c372fcf9'
down_revision: Union[str, Sequence[str], None] = '420e0f00c050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_settings', sa.Column('pattern_strength_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('pipeline_settings', sa.Column('pattern_boost_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_settings', 'pattern_boost_overrides')
    op.drop_column('pipeline_settings', 'pattern_strength_overrides')
    # ### end Alembic commands ###
