"""add cooldown columns

Revision ID: c00a664dc61d
Revises: 7501196287dd
Create Date: 2026-03-31 06:29:16.537800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00a664dc61d'
down_revision: Union[str, Sequence[str], None] = '7501196287dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_evaluations', sa.Column('suppressed_reason', sa.String(length=128), nullable=True))
    op.add_column('pipeline_settings', sa.Column('cooldown_max_candles', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_settings', 'cooldown_max_candles')
    op.drop_column('pipeline_evaluations', 'suppressed_reason')
    # ### end Alembic commands ###
