"""add regime_weights table

Revision ID: d3338889f1fd
Revises: 399ffdd585af
Create Date: 2026-03-17 19:03:59.948993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3338889f1fd'
down_revision: Union[str, Sequence[str], None] = '399ffdd585af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regime_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('trending_trend_cap', sa.Float(), nullable=False),
    sa.Column('trending_mean_rev_cap', sa.Float(), nullable=False),
    sa.Column('trending_bb_vol_cap', sa.Float(), nullable=False),
    sa.Column('trending_volume_cap', sa.Float(), nullable=False),
    sa.Column('ranging_trend_cap', sa.Float(), nullable=False),
    sa.Column('ranging_mean_rev_cap', sa.Float(), nullable=False),
    sa.Column('ranging_bb_vol_cap', sa.Float(), nullable=False),
    sa.Column('ranging_volume_cap', sa.Float(), nullable=False),
    sa.Column('volatile_trend_cap', sa.Float(), nullable=False),
    sa.Column('volatile_mean_rev_cap', sa.Float(), nullable=False),
    sa.Column('volatile_bb_vol_cap', sa.Float(), nullable=False),
    sa.Column('volatile_volume_cap', sa.Float(), nullable=False),
    sa.Column('trending_tech_weight', sa.Float(), nullable=False),
    sa.Column('trending_flow_weight', sa.Float(), nullable=False),
    sa.Column('trending_onchain_weight', sa.Float(), nullable=False),
    sa.Column('trending_pattern_weight', sa.Float(), nullable=False),
    sa.Column('ranging_tech_weight', sa.Float(), nullable=False),
    sa.Column('ranging_flow_weight', sa.Float(), nullable=False),
    sa.Column('ranging_onchain_weight', sa.Float(), nullable=False),
    sa.Column('ranging_pattern_weight', sa.Float(), nullable=False),
    sa.Column('volatile_tech_weight', sa.Float(), nullable=False),
    sa.Column('volatile_flow_weight', sa.Float(), nullable=False),
    sa.Column('volatile_onchain_weight', sa.Float(), nullable=False),
    sa.Column('volatile_pattern_weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair', 'timeframe', name='uq_regime_weights_pair_timeframe')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regime_weights')
    # ### end Alembic commands ###
