"""unify mean reversion and add squeeze cap

Revision ID: d8d18eff4af0
Revises: d3338889f1fd
Create Date: 2026-03-18 05:05:49.541144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8d18eff4af0'
down_revision: Union[str, Sequence[str], None] = 'd3338889f1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.String(length=128), nullable=False),
    sa.Column('auth_key', sa.String(length=64), nullable=False),
    sa.Column('pairs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeframes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.alter_column('news_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('pipeline_settings', sa.Column('mean_rev_rsi_steepness', sa.Float(), nullable=False, server_default='0.25'))
    op.add_column('pipeline_settings', sa.Column('mean_rev_bb_pos_steepness', sa.Float(), nullable=False, server_default='10.0'))
    op.add_column('pipeline_settings', sa.Column('squeeze_steepness', sa.Float(), nullable=False, server_default='0.1'))
    op.add_column('pipeline_settings', sa.Column('mean_rev_blend_ratio', sa.Float(), nullable=False, server_default='0.6'))
    op.add_column('regime_weights', sa.Column('trending_squeeze_cap', sa.Float(), nullable=False, server_default='12.0'))
    op.add_column('regime_weights', sa.Column('ranging_squeeze_cap', sa.Float(), nullable=False, server_default='16.0'))
    op.add_column('regime_weights', sa.Column('volatile_squeeze_cap', sa.Float(), nullable=False, server_default='22.0'))

    # Data migration: populate squeeze_cap from old bb_vol_cap budget
    op.execute("""
        UPDATE regime_weights SET
            trending_squeeze_cap = trending_bb_vol_cap * 0.55,
            ranging_squeeze_cap = ranging_bb_vol_cap * 0.57,
            volatile_squeeze_cap = volatile_bb_vol_cap * 0.79,
            trending_mean_rev_cap = trending_mean_rev_cap + trending_bb_vol_cap * 0.45,
            ranging_mean_rev_cap = ranging_mean_rev_cap + ranging_bb_vol_cap * 0.43,
            volatile_mean_rev_cap = volatile_mean_rev_cap + volatile_bb_vol_cap * 0.21
    """)

    op.drop_column('regime_weights', 'ranging_bb_vol_cap')
    op.drop_column('regime_weights', 'trending_bb_vol_cap')
    op.drop_column('regime_weights', 'volatile_bb_vol_cap')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regime_weights', sa.Column('volatile_bb_vol_cap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('regime_weights', sa.Column('trending_bb_vol_cap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('regime_weights', sa.Column('ranging_bb_vol_cap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('regime_weights', 'volatile_squeeze_cap')
    op.drop_column('regime_weights', 'ranging_squeeze_cap')
    op.drop_column('regime_weights', 'trending_squeeze_cap')
    op.drop_column('pipeline_settings', 'mean_rev_blend_ratio')
    op.drop_column('pipeline_settings', 'squeeze_steepness')
    op.drop_column('pipeline_settings', 'mean_rev_bb_pos_steepness')
    op.drop_column('pipeline_settings', 'mean_rev_rsi_steepness')
    op.alter_column('news_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
