"""add content_text to news_events

Revision ID: da3f73fd3440
Revises: add32f4a3368
Create Date: 2026-03-22 06:50:34.718339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3f73fd3440'
down_revision: Union[str, Sequence[str], None] = 'add32f4a3368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_events', sa.Column('content_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_events', 'content_text')
    # ### end Alembic commands ###
