"""add ensemble_disagreement_scale to pipeline_settings

Revision ID: da9705f5c496
Revises: 55bc9e777b6e
Create Date: 2026-03-30 20:54:01.780041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9705f5c496'
down_revision: Union[str, Sequence[str], None] = '55bc9e777b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_settings', sa.Column('ensemble_disagreement_scale', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('ensemble_stale_fresh_days', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('ensemble_stale_decay_days', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('ensemble_stale_floor', sa.Float(), nullable=True))
    op.add_column('pipeline_settings', sa.Column('ensemble_confidence_cap_partial', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_settings', 'ensemble_confidence_cap_partial')
    op.drop_column('pipeline_settings', 'ensemble_stale_floor')
    op.drop_column('pipeline_settings', 'ensemble_stale_decay_days')
    op.drop_column('pipeline_settings', 'ensemble_stale_fresh_days')
    op.drop_column('pipeline_settings', 'ensemble_disagreement_scale')
    # ### end Alembic commands ###
