"""add conviction_floor to pipeline_settings

Revision ID: f598aa9c7321
Revises: ffeee77e9608
Create Date: 2026-04-02 07:09:19.039041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f598aa9c7321'
down_revision: Union[str, Sequence[str], None] = 'ffeee77e9608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_settings', sa.Column('conviction_floor', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_settings', 'conviction_floor')
    # ### end Alembic commands ###
